### ISSUE TITLE
article.md package.json confuse people 

### ISSUE THREAD

**Issue by seven-lh** [cosmicjs/todo-app#1]
dependencies None express You server need express ! directory what descript in article that diff with this git repo !  maybe  your article need rewrite . i`m a beginner learn react&redux with bad english! 
thanks anywhay

**Comment by tonyspiro** [comment]
Thanks @seven-lh express has been added to the hacker noon article https://hackernoon.com/how-to-build-a-todo-app-using-react-redux-and-webpack-1aa99dc2f45c
